on:
  release:
    types: [published]

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Github Releases To Discord
        uses: SethCohen/github-releases-to-discord@v1.16.2
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          color: "2105893"
          username: "Changelog"
          avatar_url: "https://cdn.discordapp.com/attachments/547349889642790914/1331698953258930246/image-1.png?ex=679290cc&is=67913f4c&hm=0615f1b41fa2b6323ba8f61f40e9842516c6e009f7c21adaf873c814a7177f5c&"
          content: "||@here||"
          footer_title: "Changelog"
          footer_icon_url: "https://cdn.discordapp.com/attachments/547349889642790914/1331698953258930246/image-1.png?ex=679290cc&is=67913f4c&hm=0615f1b41fa2b6323ba8f61f40e9842516c6e009f7c21adaf873c814a7177f5c&"
          footer_timestamp: true
          max_description: '4096'
          reduce_headings: true